In [ ]:
import tensorflow as tf
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
# Constants

con1=tf.constant(10)
con2=tf.constant(3.14)
con3=tf.constant("This is tensorflow")
con4=tf.constant(True)

In [ ]:
print(con1,con2,con3,con4)

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(3.14, shape=(), dtype=float32) tf.Tensor(b'This is tensorflow', shape=(), dtype=string) tf.Tensor(True, shape=(), dtype=bool)


In [ ]:
import tensorflow as tf

# Your TensorFlow operations here (no session needed)
x = tf.constant([1, 2, 3])
y = x * 2
print(y)  # Output: tf.Tensor([2 4 6], shape=(3,), dtype=int32)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf

print(tf.__version__)

2.15.0


In [ ]:
#operations

Addition= tf.constant(20) + tf.constant(30)
Mul= tf.constant(20) * tf.constant(30)



In [ ]:
# Create a matrix (tensor)
matrix = tf.constant([1, 2, 3])+ tf.constant([4, 5, 6])

# Print the matrix
print(matrix)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [24]:
str1=tf.constant("I love ")
str2=tf.constant("tensorflow")

print(str1+str2)

tf.Tensor(b'I love tensorflow', shape=(), dtype=string)


# Placeholder

In [ ]:
a=tf.placeholder(tf.int32)
b=a*2
sess.run(b,feed_dict={a:[1,2,3,4,5]})

# output: array([2,4,6,8,10])

In [ ]:
str_name=tf.placeholder(tf.string)
my_name="I am "+str_name
sess.run(my name,feed_dic={str_name:["sam","bob","charleie"]})

# output: array([b' I am sam',b'I am bob, I am charlie]),dtype=object


# Variable

In [28]:
var1 =tf.Variable([20],tf.int32)

In [29]:
init=tf.global_variables_initializer()

AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'

# Intro to neural Network