#Random Number
Random number does NOT mean a different number every time. Random means something that can not be predicted logically

#Pseudo random
Random numbers generated through a generation algorithm are called pseudo random

In [2]:
# Generate Random Number
# NumPy offers the random module to work with random numbers.

#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

92


In [3]:
# The random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.8117190483094372


#Generate Random Array
#Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [5]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
from numpy import random
x = random.randint(100,size=5)
print(x)

[93 55 52 17  6]


In [8]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random
x = random.randint(100,size=(3,5))
print(x)

[[73 35 13 40 48]
 [16 94 34  3 61]
 [24 34 16 95 98]]


In [10]:
#Generate a 1-D array containing 5 random floats:

from numpy import random
x = random.rand(5)
print(x)

[0.13387691 0.55723991 0.34299436 0.57454161 0.63841125]


In [11]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.57966356 0.48064944 0.93651393 0.21513901 0.6624057 ]
 [0.09590888 0.58055891 0.61486987 0.87892004 0.68542857]
 [0.26240136 0.39149443 0.17637717 0.68297292 0.34847204]]


# Choice()
The choice() method allows you to generate a random value based on an array of values

In [12]:
#Return one of the values in an array:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

9


In [13]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 3 3 9]
 [5 3 3 5 5]
 [5 7 3 7 3]]


#What is Data Distribution?
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

In [15]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))

print(x)

[5 5 5 5 5 7 7 3 7 5]
